[package]
name        = "flix-pretty"
description = "A pretty print library for Flix."
version     = "0.9.2"
flix        = "0.67.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

