[package]
name        = "flix-pretty"
description = "A pretty print library for Flix."
version     = "0.9.3"
flix        = "0.67.2"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

